profiles/urls.py
from django.urls import path

from .views import (
    ProfileUpdateView,
    ProfilePublicDetailView,
    PublicProfileListView,

    # Certificados
    CertificationListView,
    CertificationCreateView,
    CertificationDetailView,
    CertificationUpdateView,
    CertificationDeleteView,

    # Habilidades
    ProfileSkillListView,
    ProfileSkillCreateView,
    ProfileSkillDetailView,
    ProfileSkillUpdateView,
    ProfileSkillDeleteView,

    # Sistemas
    ProfileSystemListView,
    ProfileSystemCreateView,
    ProfileSystemDetailView,
    ProfileSystemUpdateView,
    ProfileSystemDeleteView,
)

app_name = "profiles"

urlpatterns = [
    # Perfil
    path("edit/", ProfileUpdateView.as_view(), name="perfil_edit"),
    path("public/", PublicProfileListView.as_view(), name="perfis_publicos"),
    path("<int:pk>/public/", ProfilePublicDetailView.as_view(), name="perfis_publicos_det"),

    # Certificados
    path("certificates/", CertificationListView.as_view(), name="certificados_list"),
    path("certificates/add/", CertificationCreateView.as_view(), name="certificados_add"),
    path("certificates/<int:pk>/", CertificationDetailView.as_view(), name="certificados_det"),
    path("certificates/<int:pk>/edit/", CertificationUpdateView.as_view(), name="certificados_edit"),
    path("certificates/<int:pk>/delete/", CertificationDeleteView.as_view(), name="certificados_delete"),

    # Habilidades
    path("skills/", ProfileSkillListView.as_view(), name="habilidades_list"),
    path("skills/add/", ProfileSkillCreateView.as_view(), name="habilidades_create"),
    path("skills/<int:pk>/", ProfileSkillDetailView.as_view(), name="habilidades_detail"),
    path("skills/<int:pk>/edit/", ProfileSkillUpdateView.as_view(), name="habilidades_update"),
    path("skills/<int:pk>/delete/", ProfileSkillDeleteView.as_view(), name="habilidades_delete"),

    # Sistemas
    path("systems/", ProfileSystemListView.as_view(), name="sistemas_list"),
    path("systems/add/", ProfileSystemCreateView.as_view(), name="sistemas_create"),
    path("systems/<int:pk>/", ProfileSystemDetailView.as_view(), name="sistemas_detail"),
    path("systems/<int:pk>/edit/", ProfileSystemUpdateView.as_view(), name="sistemas_update"),
    path("systems/<int:pk>/delete/", ProfileSystemDeleteView.as_view(), name="sistemas_delete"),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from skills.models import Skill, SkillLevel, System, Function


class CertificationType(models.TextChoices):
    TECHNICAL = "technical", "Curso Técnico"

    GRADUATION = "graduation", "Graduação"
    POSTGRADUATION = "postgraduation", "Pós-graduação"
    MBA = "mba", "MBA"

    MASTER = "master", "Mestrado"
    DOCTORATE = "doctorate", "Doutorado"
    POSTDOCTORATE = "postdoctorate", "Pós-doutorado"

    COURSE = "course", "Curso"
    TRAINING = "training", "Treinamento"
    WORKSHOP = "workshop-Oficina", "Workshop/Oficina"


class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name="Usuário", on_delete=models.CASCADE, related_name="profile", unique=True,)
    registration = models.CharField(verbose_name="Matrícula", max_length=10, blank=True, null=True,)
    function = models.ForeignKey(Function, verbose_name="Cargo Efetivo", on_delete=models.PROTECT, related_name="Function", blank=True, null=True,)
    admission_date = models.DateField(verbose_name="Admissão", blank=True, null=True,)
    cpf = models.CharField(max_length=14, verbose_name="CPF", unique=True)
    phrase = models.CharField(max_length=250, verbose_name="Frase de Perfil", blank=True, null=True,)
    public = models.BooleanField(verbose_name="Perfil Público", default=True)

    def __str__(self):
        full_name = self.user.get_full_name().strip()
        return full_name or self.user.username

    @property
    def course_count(self):
        return self.certifications.filter(
            certification_type__in=[
                CertificationType.COURSE,
                CertificationType.TRAINING,
                CertificationType.WORKSHOP,
            ]
        ).count()

    @property
    def technical_count(self):
        return self.certifications.filter(
            certification_type=CertificationType.TECHNICAL
        ).count()

    @property
    def graduations_count(self):
        return self.certifications.filter(
            certification_type=CertificationType.GRADUATION
        ).count()

    @property
    def postgraduations_count(self):
        return self.certifications.filter(
            certification_type__in=[
                CertificationType.POSTGRADUATION,
                CertificationType.MBA,
            ]
        ).count()

    @property
    def masters_doctorates_count(self):
        return self.certifications.filter(
            certification_type__in=[
                CertificationType.MASTER,
                CertificationType.DOCTORATE,
                CertificationType.POSTDOCTORATE,
            ]
        ).count()


class Certification(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="certifications", verbose_name="Perfil",)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Cadastro")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Alteração")

    certification_type = models.CharField(
        "Tipo de Certificação",
        max_length=20,
        choices=CertificationType.choices,
        default=CertificationType.COURSE,
    )

    name = models.CharField("Nome da Certificação", max_length=200)
    institution = models.CharField("Instituição", max_length=200)
    workload = models.PositiveIntegerField("Carga Horária", null=True, blank=True,)
    issue_date = models.DateField("Data de Emissão")

    file = models.FileField(
        "Arquivo (PDF)",
        upload_to="certifications/%Y/%m/",
        null=True,
        blank=True,
    )

    link = models.URLField(
        "Link do Certificado",
        max_length=500,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("-issue_date",)
        verbose_name = "Certificado"
        verbose_name_plural = "Certificados"

    def __str__(self):
        return self.name


class ProfileSkill(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="skills",)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Cadastro")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Alteração")

    skill = models.ForeignKey(Skill, on_delete=models.CASCADE, related_name="profiles", verbose_name="Habilidade",)
    level = models.IntegerField(choices=SkillLevel.choices, verbose_name="Nível", default=SkillLevel.ROBOTIC)
    notes = models.TextField("Observações", blank=True,)

    class Meta:
        unique_together = ("profile", "skill")
        verbose_name = "Habilidade do Perfil"
        verbose_name_plural = "Habilidades por Perfil"
        ordering = ("-level", "skill")

    def __str__(self):
        return f"{self.skill} - {self.get_level_display()}"


class ProfileSystem(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="systems", verbose_name="Perfil",)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Cadastro")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Alteração")

    system = models.ForeignKey(System, on_delete=models.CASCADE, related_name="profiles", verbose_name="Sistema",)
    level = models.IntegerField(choices=SkillLevel.choices, verbose_name="Nível", default=SkillLevel.ROBOTIC)
    notes = models.TextField("Observações", blank=True,)

    class Meta:
        unique_together = ("profile", "system")
        verbose_name = "Sistema do Perfil"
        verbose_name_plural = "Sistemas por Perfil"
        ordering = ("-level", "system")

    def __str__(self):
        return f"{self.system} - {self.get_level_display()}"

profiles/templates/profiles/certification/certification_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Certificações
{% endblock title %}

{% block content %}

    <h2>📜 Certificações</h2>

    <form method="get" class="my-3">
        <div class="row">
            <div class="col-12 col-md-9">

                <label class="form-label">Pesquisar:</label>

                <div class="input-group">
                    <select name="type" class="form-select">
                        <option value="">Todos Tipos</option>
                        {% for value, label in types %}
                            <option value="{{ value }}"
                                    {% if request.GET.type == value %}selected{% endif %}>
                                {{ label }}
                            </option>
                        {% endfor %}
                    </select>

                    <input
                        type="text"
                        name="q"
                        value="{{ request.GET.q }}"
                        class="form-control"
                        autocomplete="off"
                        placeholder="Certificação ou Instituição"
                    >

                    <button class="btn btn-primary" type="submit">
                        <i class="bi bi-search"></i>
                    </button>

                    {# BOTÃO LIMPAR #}
                    {% if request.GET.q or request.GET.type %}
                        <a href="{% url 'profiles:certificados_list' %}" class="btn btn-warning" title="Limpar filtros">
                            <i class="bi bi-x-lg"></i>
                        </a>
                    {% endif %}

                </div>
            </div>

            <div class="col-12 col-md-3 align-self-end text-sm-center text-md-end">
                <a class="btn btn-success" href="{% url 'profiles:certificados_add' %}">
                    <i class="bi bi-window-plus"></i>
                    Novo
                </a>
            </div>
        </div>
    </form>


    {% if certifications %}
        <div class="table-responsive">
            <table class="table table-sm align-middle table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">Data:</th>
                        <th scope="col">Tipo:</th>
                        <th scope="col">Instituição:</th>
                        <th scope="col">Certificação:</th>
                        <th scope="col">CH:</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cert in certifications %}
                        <tr>
                            <td>{{ cert.issue_date }}</td>
                            <td>{{ cert.get_certification_type_display }}</td>
                            <td>{{ cert.institution }}</td>
                            <td>{{ cert.name }}</td>
                            <td>{{ cert.workload|default:"" }}</td>
                            <td class="text-end">

                                {% if cert.file %}
                                    <a class="btn btn-sm btn-primary"
                                       href="{{ cert.file.url }}"
                                       target="_blank"
                                       title="Visualizar PDF">
                                        <i class="bi bi-file-earmark-pdf"></i>
                                    </a>
                                {% elif cert.link %}
                                    <a class="btn btn-sm btn-primary"
                                       href="{{ cert.link }}"
                                       target="_blank"
                                       title="Acessar link do certificado">
                                        <i class="bi bi-box-arrow-up-right"></i>
                                    </a>
                                {% else %}
                                    <a class="btn btn-sm btn-primary disabled" href="#" tabindex="-1" aria-disabled="true" title="Nenhum PDF disponível">
                                        <i class="bi bi-file-earmark-x"></i>
                                    </a>
                                {% endif %}

                                <a class="btn btn-sm btn-info" href="{% url 'profiles:certificados_det' cert.pk %}" title="Detalhes">
                                    <i class="bi bi-search"></i>
                                </a>

                                <button title="Deletar" class="btn btn-sm btn-danger"  data-bs-toggle="modal" data-bs-target="#delete-{{item.pk}}">
                                    <i class="bi bi-trash3"></i> 
                                </button>

                            </td>
                        </tr>

                        {% include "profiles/certification/modal_delete.html" %}

                    {% empty %}
                        <tr>
                            <td colspan="6" class="text-muted text-center py-3">

                                Nenhuma certificação cadastrada.
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="text-center my-4">
            <div class="col-12 col-md-6 mx-auto">
                <div class="alert alert-info d-flex justify-content-center align-items-center gap-2" role="alert">
                    <span>Nenhuma certificação cadastrada.</span>
                </div>
            </div>
        </div>
    {% endif %}


    {% include "pagination.html" %}


{% endblock content %}