profiles/urls.py
from django.urls import path

from .views import (
    ProfileUpdateView,
    ProfilePublicDetailView,
    PublicProfileListView,

    # Certificados
    CertificationListView,
    CertificationCreateView,
    CertificationDetailView,
    CertificationUpdateView,
    CertificationDeleteView,

    # Habilidades
    ProfileSkillListView,
    ProfileSkillCreateView,
    ProfileSkillDetailView,
    ProfileSkillUpdateView,
    ProfileSkillDeleteView,

    # Sistemas
    ProfileSystemListView,
    ProfileSystemCreateView,
    ProfileSystemDetailView,
    ProfileSystemUpdateView,
    ProfileSystemDeleteView,
)

app_name = "profiles"

urlpatterns = [
    # Perfil
    path("edit/", ProfileUpdateView.as_view(), name="perfil_edit"),
    path("public/", PublicProfileListView.as_view(), name="perfis_publicos"),
    path("<int:pk>/public/", ProfilePublicDetailView.as_view(), name="perfis_publicos_det"),

    # Certificados
    path("certificates/", CertificationListView.as_view(), name="certificados_list"),
    path("certificates/add/", CertificationCreateView.as_view(), name="certificados_add"),
    path("certificates/<int:pk>/", CertificationDetailView.as_view(), name="certificados_det"),
    path("certificates/<int:pk>/edit/", CertificationUpdateView.as_view(), name="certificados_edit"),
    path("certificates/<int:pk>/delete/", CertificationDeleteView.as_view(), name="certificados_delete"),

    # Habilidades
    path("skills/", ProfileSkillListView.as_view(), name="habilidades_list"),
    path("skills/add/", ProfileSkillCreateView.as_view(), name="habilidades_create"),
    path("skills/<int:pk>/", ProfileSkillDetailView.as_view(), name="habilidades_detail"),
    path("skills/<int:pk>/edit/", ProfileSkillUpdateView.as_view(), name="habilidades_update"),
    path("skills/<int:pk>/delete/", ProfileSkillDeleteView.as_view(), name="habilidades_delete"),

    # Sistemas
    path("systems/", ProfileSystemListView.as_view(), name="sistemas_list"),
    path("systems/add/", ProfileSystemCreateView.as_view(), name="sistemas_create"),
    path("systems/<int:pk>/", ProfileSystemDetailView.as_view(), name="sistemas_detail"),
    path("systems/<int:pk>/edit/", ProfileSystemUpdateView.as_view(), name="sistemas_update"),
    path("systems/<int:pk>/delete/", ProfileSystemDeleteView.as_view(), name="sistemas_delete"),
]

profiles/templates/skills/modal_delete.html
<div class="modal fade" id="delete-{{ skill.pk }}" tabindex="-1">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <!-- Cabeçalho vermelho -->
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title">
                    <i class="bi bi-trash3"></i>
                    Apagar
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <p class="mb-2">Deseja excluir o registro?</p>
                <p class="small"><b>Habilidade:</b> {{ skill.skill.name }}</p>
                <p class="small text-muted mb-0">* Esta ação não poderá ser desfeita</p>
            </div>

            <div class="modal-footer">
                <form method="post" action="{% url 'profiles:habilidades_delete' skill.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                        <i class="bi bi-check-lg"></i>
                        Confirmar
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        <i class="bi bi-x-lg"></i>
                        Cancelar
                    </button>
                </form>
            </div>

        </div>
    </div>
</div>

profiles/templates/skills/skill_create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Certificações
{% endblock title %}

{% block content %}

    <h2>🧠 Adicionar Habilidades</h2>

    <div class="container mt-4">

        <form class="row" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="col-sm-12 col-md-8 mb-3">
                <label for="{{ form.skill.id_for_label }}" class="form-label">{{ form.skill.label }}: {% if form.skill.field.required %}<span class="text-danger">*</span>{% endif %}</label>
                {% render_field form.skill class="form-select" %}
                {% for error in form.skill.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                <div class="invalid-feedback">
                    Este campo é obrigatório
                </div>
            </div>

            <div class="col-sm-6 col-md-2 mb-3">
                <label for="{{ form.level.id_for_label }}" class="form-label">{{ form.level.label }}: {% if form.level.field.required %}<span class="text-danger">*</span>{% endif %}</label>
                {% render_field form.level class="form-select" %}
                {% for error in form.level.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                <div class="invalid-feedback">
                    Este campo é obrigatório
                </div>
            </div>

            <div class="col-sm-6 col-md-2 mb-3">
                <label for="{{ form.years_experience.id_for_label }}" class="form-label">{{ form.years_experience.label }}: {% if form.years_experience.field.required %}<span class="text-danger">*</span>{% endif %}</label>
                {% render_field form.years_experience class="form-control" %}
                {% for error in form.years_experience.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                <div class="invalid-feedback">
                    Este campo é obrigatório
                </div>
            </div>

            <div class="col-12 mb-3">
                <div class="g-1">
                    <!-- ===== BOTOES ===== -->
                    {% if not is_detail %}
                        <button type="submit" class="btn btn-success me-1">
                            <i class="bi bi-check-lg me-1"></i> Salvar
                        </button>
                        <button type="reset" class="btn btn-warning me-1">
                            <i class="bi bi-x me-1"></i> Limpar
                        </button>
                    {% else %}
                        <a href="{% url 'profiles:habilidades_update' skill.pk %}" title="Editar Registro" class="btn btn-primary me-1">
                            <i class="bi bi-pencil"></i> Editar
                        </a>
                    {% endif %}
                    <button type="button" onclick="window.history.go(-1)" class="btn btn-secondary">
                        <i class="bi bi-arrow-return-left me-1"></i>Voltar
                    </button>
                </div>
            </div>
        </form>
    </div>
        

{% endblock content %}

profiles/templates/skills/skill_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Habilidades
{% endblock title %}

{% block content %}

    <h2>🧠 Habilidades</h2>

    <form method="get" class="my-3">
        <div class="row">
            <div class="col-12 col-md-9">

                <label class="form-label">Filtros:</label>

                <div class="input-group">

                    {# FILTRO POR TIPO DE SKILL #}
                    <select name="skill_type" class="form-select">
                        <option value="">Todos Tipos</option>
                        {% for value, label in skill_types %}
                            <option value="{{ value }}"
                                {% if request.GET.skill_type == value %}selected{% endif %}>
                                {{ label }}
                            </option>
                        {% endfor %}
                    </select>

                    {# FILTRO POR NÍVEL #}
                    <select name="level" class="form-select">
                        <option value="">Todos Níveis</option>
                        {% for value, label in levels %}
                            <option value="{{ value }}"
                                {% if request.GET.level == value %}selected{% endif %}>
                                {{ label }}
                            </option>
                        {% endfor %}
                    </select>

                    {# PESQUISA POR NOME #}
                    <input
                        type="text"
                        name="q"
                        value="{{ request.GET.q }}"
                        class="form-control"
                        placeholder="Habilidade"
                    >

                    <button class="btn btn-primary" type="submit">
                        <i class="bi bi-search"></i>
                    </button>

                    {# BOTÃO LIMPAR #}
                    {% if request.GET.q or request.GET.level or request.GET.skill_type %}
                        <a href="{% url 'profiles:habilidades_list' %}" class="btn btn-warning" title="Limpar filtros">
                            <i class="bi bi-x-lg"></i>
                        </a>
                    {% endif %}
                </div>

            </div>

            <div class="col-12 col-md-3 align-self-end text-sm-center text-md-end">
                <a class="btn btn-success" href="{% url 'profiles:habilidades_create' %}">
                    <i class="bi bi-window-plus"></i>
                    Novo
                </a>
            </div>
        </div>
    </form>

    {% if skills %}
        <div class="table-responsive">
            <table class="table table-sm align-middle table-striped table-hover">
                <thead>
                    <tr>
                        <th>Habilidade</th>
                        <th>Tipo</th>
                        <th>Nível</th>
                        <th>Observações</th>
                        <th class="text-end"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for skill in skills %}
                        <tr>
                            <td>{{ skill.skill.name }}</td>
                            <td>{{ skill.skill.get_skill_type_display }}</td>
                            <td>{{ skill.get_level_display }}</td>
                            <td>
                                {% if skill.notes %}
                                    {{ skill.notes|truncatewords:12 }}
                                {% else %}
                                    <span class="text-secondary">—</span>
                                {% endif %}
                            </td>
                            <td class="text-end">
                                <a class="btn btn-sm btn-info"
                                   href="{% url 'profiles:habilidades_detail' skill.pk %}"
                                   title="Detalhes">
                                    <i class="bi bi-search"></i>
                                </a>

                                <button title="Deletar" class="btn btn-sm btn-danger"  data-bs-toggle="modal" data-bs-target="#delete-{{skill.pk}}">
                                    <i class="bi bi-trash3"></i> 
                                </button>
                            </td>
                            {% include "skills/modal_delete.html" %}
                        </tr>

                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-muted text-center py-3">
                                Nenhuma habilidade cadastrada.
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    {% else %}
        <div class="text-center my-4">
            <div class="col-12 col-md-6 mx-auto">
                <div class="alert alert-info d-flex justify-content-center align-items-center gap-2" role="alert">
                    <span>Nenhuma habilidade cadastrada.</span>
                </div>
            </div>
        </div>
    {% endif %}

    {% include "pagination.html" %}

{% endblock content %}